#!/usr/bin/env bash
# A Bash script that kills the 7-highlander process using SIGKILL

# Find all PIDs of 7-highlander
pids=$(pgrep -f 7-highlander)

# Kill each PID if exists
for pid in $pids; do
  kill -9 "$pid"
done
